### ISSUE TITLE
Can't find variable: internal

### ISSUE THREAD

**Issue by colinaut** [shalomscott/eleventy-plugin-embed-svelte#5]
Tried using this on an 11ty site I'm building and it didn't work. Then tried to use it on a bare bones 11ty basically copying your example and it also failed with the same error. 

It builds but with the following error:

```
'svelte/internal' is imported by svelte/Greeter.svelte, but could not be resolved – treating it as an external dependency
No name was provided for external module 'svelte/internal' in output.globals – guessing 'internal'
```
Then when I load it in the browser I get `Can't find variable: internal error` in the browser console.

**Comment by colinaut** [comment]
I uploaded the simple test to this [repo here](https://github.com/colinaut/11ty-svelte-test-simple)

**Comment by shalomscott** [comment]
Hi, I am not experiencing the issue you're describing. Did you make sure to `npm install` the `svelte` package? `svelte` is a peerDependency of this plugin. I'm going to mark this as closed for now.
